services:
  api-1:
    build: .
    restart: unless-stopped
    container_name: rbrcareers-api-1
    ports:
      - "3000:5000"
    env_file:
      - .env
  api-2:
    build: .
    restart: unless-stopped
    container_name: rbrcareers-api-2
    ports:
      - "3001:5000"
    env_file:
      - .env
    